build:
  image: iwan/ruby-alpine:latest
  commands:
    - gem update bundler
    - bundle install --path vendor/bundle
    - bundle exec rake db:create db:schema:load
    - bin/rspec

  environment:
    RACK_ENV: test
    RAILS_ENV: test
    SECRET_KEY_BASE: kSJDNksjdgnkSNDMsFDAD
    TEST_DB_USER: postgres

compose:
  database:
    image: postgres:9.5.1

