default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: base-rails5_development

test:
  <<: *default
  database: base-rails5_test
  username: <%= ENV['TEST_DB_USER'] %>


production:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
